### ISSUE TITLE
M1 Compatability?

### ISSUE THREAD

**Issue by hanskokx** [alyssaxuu/later#4]
Is there M1 compatability?

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1911919/188295020-c6aeadda-9104-48a8-aba2-7438af54c7a7.png">

<img width="1800" alt="Screen Shot 2022-09-03 at 10 53 41 PM" src="https://user-images.githubusercontent.com/1911919/188295011-4f2bb724-5e94-44d2-b23b-86115f043c08.png">

**Comment by fuadop** [comment]
Hi @hanskokx , Yes it is compatible, you just have to give your computer access to run it.

**Comment by fuadop** [comment]
Follow this guide I made below on how to make it run 👇 

https://user-images.githubusercontent.com/65264054/188308256-42c8db73-2262-4b7a-9932-4130348b19d3.mp4

**Comment by pressdarling** [comment]
This is addressed in the readme:

> Installing Later
> You can install Later on macOS 11.6 or later.
> 
> [Click here](https://github.com/alyssaxuu/later/raw/master/Later.dmg) to download the latest version. You can also download the [Later.dmg](https://github.com/alyssaxuu/later/blob/master/Later.dmg) file from this repo.
> Drag the Later app into the Applications folder.
> Right click while holding the Control key on the Later app, and select "Open" from the context menu.
> **You will be prompted with an alert saying that the app can't be opened because Apple cannot check it for malicious software (it's not signed). You can open it anyway by clicking "Open".**
> Later will open as an item on your menu bar.
